language: python
python:
- '2.7'

branches:
  only:
    - master

install: echo 'no install'

script: echo 'no scripts'

before_install: chmod +x ./.build_scripts/deploy.sh

after_success: ./.build_scripts/deploy.sh
